### ISSUE TITLE
window.fetch() incompatible with Safari

### ISSUE THREAD

**Issue by jamesprices** [IronCountySchoolDistrict/iep-printing-php#8]
The IEP Management page does not work in Safari because window.fetch() doesn't exist in its API. I'm working on a solution, but if you have any ideas let me know. It also isn't compatible with IE, but if someone is trying to use IE still they have other issues...

**Comment by jonesnc** [comment]
We've included this [polyfill](https://github.com/github/fetch) in the past with other projects, but I thought we were okay not to include it on newer versions of Safari. I can include this going forward.
